name: sre-go-interview

services:
  weather-service:
    build: .
    ports: ["8080:8080"]
    networks: [monitoring]

  dashboard-ui:
    image: nginx:alpine
    volumes: ["./dashboard:/usr/share/nginx/html"]
    ports: ["8081:80"]
    networks: [monitoring]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./internal/obs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./internal/obs/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports: ["9090:9090"]
    networks: [monitoring]

  grafana:
      image: grafana/grafana:latest
      ports: ["3000:3000"]
      volumes:
        # Mount the configuration that tells Grafana to look for dashboards
        - ./grafana/provisioning:/etc/grafana/provisioning
        # Mount the actual JSON files
        - ./grafana/dashboards:/var/lib/grafana/dashboards
      environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      networks: [monitoring]

networks:
  monitoring:
    driver: bridge