global:
  scrape_interval: 5s # Fast scraping for real-time dashboard updates
  evaluation_interval: 5s

rule_files:
  - "/etc/prometheus/alert_rules.yml" # Pointing to the internal container path

scrape_configs:
  - job_name: 'weather-service'
    static_configs:
      # Use the service name defined in docker-compose
      - targets: ['weather-service:8080']