global:
  scrape_interval: 5s # Fast scrape for demo purposes

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'weather-service'
    static_configs:
      - targets: ['weather-service:8080']