global:
  scrape_interval: 5s 
  evaluation_interval: 5s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'weather-service'
    static_configs:
      - targets: ['weather-service:8080'] 
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']